title: Welcome to my blog, I'm Jay Fursule
author: Jay Fursule
email: jayesh.f1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Ready to help you whenever i'm free and try to solve your query.
 I'm glad to share my interest, knowlage with anyone. and I am interested 
 in new technology, software devlopment, software testing, photography,
 musical instruments like keyboard, octopad...
# social links
twitter_username: jay_fursule
github_username:  jayfursule
instagram_username: jay_fursule
youtube_channel: Jay Fursule

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-dinky
